exports.PASSWORD_NOT_CORRECT = "{ error: 'password is not correct' , errorCode:'001'}";
exports.USER_NOT_EXIST = "{ error: 'user does not exist' , errorCode:'002'}";
exports.INTERNAL_ERROR = "{ error: 'internal error occur!' , errorCode:'003'}";
exports.PERMISSION_ERROR = "{ error: 'permission error' , errorCode:'004'}";
exports.ARGUMENT_MISTAKE = "{ error: 'argument has mistake' , errorCode:'005'}";
exports.MEDIA_NOT_EXIST = "{ error: 'media file does not exist' , errorCode:'006}";
exports.CRYPTO_ERROR = "{ error: 'crypto error' , errorCode:'007}";
exports.MONGO_DB_ERROR = "{ error: 'mongo db error' , errorCode:'008'}";
exports.USER_ALREADY_EXIST = "{ error: 'user already existed' , errorCode:'009'}";